FROM rueberger/dense-correspondence

USER andrew

WORKDIR /home/andrew/

RUN git clone https://github.com/rueberger/pytorch-dense-correspondence.git && \
    ln -s /home/andrew/pytorch-dense-correspondence /home/andrew/code
