version: '3.4'
services:
  dense-seg:
    build:
      context: dense-seg/
    image: 'rueberger/dense-correspondence:latest'
    networks:
      - core
    volumes:
      - '/data/dense_seg:/home/andrew/code/data_volume'
      - 'torch:/home/andrew/torch'
    ports:
      - '172.30.116.35:9999:8888'


networks:
  core:
    driver: overlay
    attachable: true

volumes:
  torch:
